# mcp/wrangler.toml

name               = "mcp-server"
main               = "src/index.mjs"
compatibility_date = "2025-05-05"
account_id         = "8bfd3f60fbdcc89183e9e312fb03e86e"

[env.production]
zone_id = "b298c4645feb8f945eb1a0950eb24323"
routes  = [
  "this-is-us.org/api/candidates/*",
  "this-is-us.org/api/files/*",
  "this-is-us.org/api/warriors*"
]

# R2 bucket for PDFs
[[env.production.r2_buckets]]
binding             = "CANDIDATE_PDFS"
bucket_name         = "event-pdfs-bucket"
preview_bucket_name = "event-pdfs-bucket-preview"

# D1 database for candidates
[[env.production.d1_databases]]
binding              = "CANDIDATES_DB"
database_name        = "events_db"
database_id          = "b5814930-2779-4bfb-8052-24ee419e09fd"
preview_database_id  = "1624450c-f228-4802-8a76-9c65f29295fa"

# OpenAI binding
[env.production.ai]
binding = "AI"
