name = "mcp-server"
main = "src/index.mjs"
compatibility_date = "2025-05-05"

[ai]
binding = "AI"

[[d1_databases]]
binding              = "CANDIDATES_DB"
database_name        = "events_db"  # Reuses the same D1 for now
database_id          = "b5814930-2779-4bfb-8052-24ee419e09fd"
preview_database_id  = "1624450c-f228-4802-8a76-9c65f29295fa"

[[r2_buckets]]
binding             = "CANDIDATE_PDFS"
bucket_name         = "event-pdfs-bucket"
preview_bucket_name = "event-pdfs-bucket-preview"
local_dir           = "./local‑pdfs"
